### ISSUE TITLE
Site redesign

### ISSUE THREAD

**Issue by marykatefain** [dxe/dxephilly.org#17]
Suggested draft:

![about](https://user-images.githubusercontent.com/17955536/27005895-cc7e4f20-4df5-11e7-9a9c-548c528b61e0.png)

**Comment by marykatefain** [comment]
Not finished obviously, but you get the gist. @alexgleason how does this look?

**Comment by marykatefain** [comment]
Also hoping we can create this as a template that any chapter could use by just replacing their own logo and events

**Comment by alexgleason** [comment]
1. The navigation is placed in a weird position. I don't think it should be under the banner like that.
2. The font in the navigation is bad. It's overkill.
3. I'm not sure what the "3 columns" thing is trying to accomplish. It's quite overused in web design. I *do* like the big "join the movement" headline. I'm just wondering if this can be done differently. Where is teh call to action? Where are you trying to lead them? You have to guide the user through the site somehow.
4. The button doesn't look enough like a button. Something is off, but I can't quite put my finger on it. At the very least it needs more padding.
5. Unsure of the purpose of the 3 dots at the bottom.

I feel like the biggest issue I have is just that you aren't really thinking about who the reader is, why they're there, and then guiding them to where they need to go. Maybe you should write out who these people are and we can figure out how to get them there.

All this said, I'm not going to block you from getting started, just wanting to give you my thoughts. This is still an improvement over what we have.

**Comment by alexgleason** [comment]
I bring up this site occasionally, but I just want to throw it back in as a website that I consider *pristine*. Even the dumbest person would be easily guided through this site. http://hydrokinetics.com/

**Comment by marykatefain** [comment]
2, 4, 5: Lol it's literally just a super basic draft so you get the gist... This isn't even the DxE font, just the closest thing they had on the program I was using to throw it together. I didn't feel like going the whole way down with the thing so the "..." is like "continue with other stuff if you want idk" SUPER BASIC MOCKUP.

1: Do you want it above the banner?

3: Showing multiple images and options at once so people don't have to search that hard for the basics. Send better ideas if you have them. Easily converts to mobile by going vertical

**Comment by marykatefain** [comment]
I find that site example very hard to read and navigate without a nav bar ^

**Comment by alexgleason** [comment]
But what purpose does the website serve? When do people access it? Do we put it on pamphlets, and then people interested in joining us view it? Then we need to guide them to become activists. It may require telling a story.

What do you think a person going to our website will be thinking?

**Comment by marykatefain** [comment]
It should provide information about what we do, why we do it, and how to get involved

**Comment by alexgleason** [comment]
But why?

**Comment by marykatefain** [comment]
Because those are things people don't know but they need to know

**Comment by alexgleason** [comment]
People go to a website to find information that *they* want, not to have information that you want them to know become absorbed.

**Comment by marykatefain** [comment]
Alright, handing this off to you then since you seem to have a different vision and are lead on the tech team. Please have a draft completed by Wednesday and work started by next weekend. I'd like it to be pretty much ready to go by the end of the month.

**Comment by alexgleason** [comment]
That is incredibly childish. I'm not blocking you, just trying to help you.

**Comment by marykatefain** [comment]
I'm booting it back up the chain of command until there's a more clear plan of attack. It sounds like you want to facilitate a tech team meeting on the purpose and direction of the site, or otherwise provide some clear direction. Taking a pause and stepping back when there is lack of clarity is the appropriate thing to do.

**Comment by marykatefain** [comment]
Closing and deleting this issue since we are name-calling. I'll reopen a new issue regarding the purpose and direction of the site.
